//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_hang2
{
    public partial class Contact
    {
        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        protected global::System.Web.UI.WebControls.Button btnSend;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}